export const SAMPLE_MATERIALS = [
    {
        id: "user-experience-optimization",
        type: "quiz",
        title: "5 Steps Optimizing User Experience",
        tags: ["UI/UX Design"],
        totalItems: 20,
        itemType: "Question",
        isPriority: true,
        certified: true,
        progress: 0,
    },
    {
        id: "usability-principles",
        type: "page",
        title: "Heuristics: 10 Usability Principles To improve UI Design",
        tags: ["Learning Design", "Not Urgent"],
        totalItems: 12,
        itemType: "Chapters",
        isPriority: false,
        progress: 40,
    },
    {
        id: "general-knowledge",
        type: "learning-path",
        title: "General Knowledge & Methodology - Layout & Spacing",
        tags: ["Consistency"],
        totalItems: 20,
        itemType: "Path",
        isPriority: false,
        progress: 0,
    },
    {
        id: "ui-design-mastery",
        type: "course",
        title: "Mastering UI Design for Impactful Solutions",
        tags: ["UI/UX Design"],
        totalItems: 12,
        itemType: "Materials",
        isPriority: false,
        progress: 50,
    },
    {
        id: "accessibility-best-practices",
        type: "course",
        title: "Accessibility Best Practices for Inclusive Design",
        tags: ["Accessibility", "UI/UX Design"],
        totalItems: 15,
        itemType: "Materials",
        isPriority: true,
        progress: 20,
    },
    {
        id: "color-theory-essentials",
        type: "quiz",
        title: "Color Theory Essentials for Digital Designers",
        tags: ["Visual Design"],
        totalItems: 25,
        itemType: "Question",
        isPriority: false,
        certified: true,
        progress: 100,
    },
    {
        id: "responsive-design-fundamentals",
        type: "learning-path",
        title: "Responsive Design Fundamentals: From Concept to Implementation",
        tags: ["Front-end", "Responsive Design"],
        totalItems: 18,
        itemType: "Path",
        isPriority: true,
        progress: 75,
    },
    {
        id: "user-research-methods",
        type: "page",
        title: "User Research Methods for Effective UX Design",
        tags: ["Research", "UI/UX Design"],
        totalItems: 10,
        itemType: "Chapters",
        isPriority: false,
        progress: 0,
    }
];